### PR TITLE
[TASK] Ignore platform requirements for LocalInstallTask

### PR DESCRIPTION
**Pull request by t3easy**
As localhost that installs the application is not the same system that runs the application, it is useless to check the platform requirements.

### CODE REVIEW

**Comment by kaystrobach** [comment]
will you add a remote requirements check as well?

**Comment by t3easy** [comment]
> will you add a remote requirements check as well?

How would you do this if there is no composer on the target node?

**Comment by kaystrobach** [comment]
interesting question - maybe transfer the phar, execute it and delete it?

**Comment by chriwo** [comment]
In my case I have set this option in the application with
`$application->setOption('additionalArguments', ['--ignore-platform-reqs'])`

Sure, the option naming is not clear, but I think it solve the problem without change the code.

**Comment by kaystrobach** [comment]
@chriwo imho the patch is valid and correct. a followup may check the remote env.

**Comment by t3easy** [comment]
I don't think it is necessary to check the target node as the dev system should have the same php+ext like production.

**Comment by kaystrobach** [comment]
Just created #299 to not pollute that MR further.

**Pull request merged**
