### PR TITLE
Task/259

### PR DESCRIPTION
**Pull request by t3easy**
* **Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bugfix

* **What is the current behavior?** (You can also link to an open issue here)
Some task that are added by before/afterTask are not visible if they are not in the same all.

* **What is the new behavior (if this is a feature change)?**
Show before/after tasks of the same and all apps 

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

### CODE REVIEW

**Comment by simonschaufi** [comment]
@t3easy please use proper titles ;)

**Comment by t3easy** [comment]
This PR is for branch 2.0, not for master
https://github.com/TYPO3/Surf/blob/2.0/.editorconfig#L9

**Comment by t3easy** [comment]
> @t3easy please use proper titles ;)
I would have done that during squash and merge ;)

**Comment by simonschaufi** [comment]
ok, next time ;)

**Pull request merged**
