### PR TITLE
[TASK] Example file for flow 3.x

### PR DESCRIPTION
**Pull request by kaystrobach**
Related #145

* **Please check if the PR fulfills these requirements**

- [ ] Tests for the changes have been added (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

- Add example Config for Flow 3.x

* **What is the current behavior?** (You can also link to an open issue here)

- no example given

* **What is the new behavior (if this is a feature change)?**

- have an example.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

- no

* **Other information**:

### CODE REVIEW

**Comment by kaystrobach** [comment]
Question is, how we document the ENV vars, they are currently defined in the head of the file -.-

**Comment by kaystrobach** [comment]
I would also prefer to have a common set of env vars as far as possible

**Comment by sabbelasichon** [comment]
@kaystrobach Thanks. Could you provide a shorter example for a Neos-Deployment. We would like to integrate examples but less complex.

@Sebobo Could you show also an example of a Neos-Deployment? Would be great.

**Comment by kaystrobach** [comment]
Will take a look.

**Comment by Sebobo** [comment]
@kaystrobach this is now very outdated code wise. Do you still want to adjust and update it, or should we just close and have another example?

**Comment by sabbelasichon** [comment]
@kaystrobach I am going to close this PR, because for the moment i think we should only ship really small examples with the documentation. If we have finally released the stable version 2.0.0 we can still ship examples with the code itself. 

#173

**Pull request closed without merging**
