### PR TITLE
[TASK] Adds configurable opt. projectRootPath setting for Composer

### PR DESCRIPTION
**Pull request by fe-hicking**
Resolves https://github.com/TYPO3/Surf/issues/398

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
(I'm sorry, but not sure how to add a test for this feature)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature: A project's root path can be configured, so that the composer.json can be stored outside of the root (i.e. in a /server1, /server2 or /htdocs subdirectory where the rest of the distinct projects live).

* **What is the current behavior?** (You can also link to an open issue here)
Currently, composer.json is only looked for inside the project root

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by simonschaufi** [comment]
looks good but please add a test for it

**Comment by fe-hicking** [comment]
Please instruct me how to do that, I‘ve never tried that, sorry.

**Comment by simonschaufi** [comment]
there are plenty of existing tests available already. have a look at them. Shouldn't be really difficult to adjust existing ones. Then execute phpunit with `vendor/bin/phpunit`

**Comment by fe-hicking** [comment]
I've looked at the existing tests. They all refer to actual composer performed commands. 

My patch affects only whether composerManifestsExists returns true or false. Am I right in assuming that this method would need to get an Exception added? Like in the Tests/Unit/Task/Composer/InstallTaskTest.php I see a noComposerCommandPathGivenThrowsException() method that works on an exception. But that would probably mean a breaking change then, because currently an exception is not thrown.

I only have superficilial knowledge of SURF and Unit-Tests. I can report that my patch works in my environment, but I would be sad if the implementation dies at this point. If you can specifically outline what I can/need to do, I'd be really happy to learn from that and try it.

**Comment by simonschaufi** [comment]
how about doing some more magic in `\TYPO3\Surf\Domain\Model\Deployment::getApplicationReleasePath()` to generalize this as not only composer will be run under this path but also anything else like `flow` or `vendor/bin/typo3`

**Comment by garvinhicking** [comment]
Thanks for getting back to me, and thanks to sabbelasichon for adding a test.

I must admit I do not know about the possible influences the applicationReleasepath would have, if a directory like this prefix for composer.json (`htdocs` in our case) would be added to every returned instance of that. Currently it is not needed for us, the default workflow "just works" with that single patch above for the composer.json location.

Also, we would then need to not only patch getApplicationreleasepath but also getWorkspacePath, because that also resolves the path to the composer.json manifest? 

All in all I am not sure this would be needed and might have more possible dangerous drawbacks or regressions than advantages. But you are surely more experienced in the flow of things, and I'm happy to follow your lead.

It wouldn't really matter to me how this could get implemented, as long as we have a way to make the deployment work when composer.json is not in the root path... ;-)

**Comment by simonschaufi** [comment]
I prepared a patch with the modification of the path yesterday and it worked out perfectly. This is the expected directory structure:

- .git
- htdocs
  - composer.json
  - index.php

so by appending `htdocs` to every path, i get the correct project base path. I haven't tried it with your patch yet but I wonder how the deployment would find typo3 console in your case

**Comment by garvinhicking** [comment]
We usually have this structure to be precise:

* .git
* htdocs
    * composer.json
    * web
        * index.php
        * typo3conf/ext/custom_extension etc.
    * vendor [autocreated]

The deployments' documentRoots are set to a directory like /var/www/releases/current/htdocs/web then. 

In our deployment config we have set 'webDirectory' to 'htdocs/web'. The rest just works (tm)...

I'm happy to try out your patch to see if it works out for us, did you commit it somewhere already?

**Comment by simonschaufi** [comment]
ah ok, probably it works because you have set the 'webDirectory' to 'htdocs/web' with typo3 console. Let me do some more tests. I haven't uploaded it yet.

**Comment by garvinhicking** [comment]
Sure, let me know when/how I can help. 

And yes, the webDirectory is AFAIR forwarded to typo3console calls. We have some very few edge cases in which we use 

```
'phpBinary' =  'TYPO3_PATH_ROOT=/path/to/typo3/root/ /usr/bin/php';
```

as a way to let the live site know where the TYPO3 installation resides. We use that only on sites where the documentRoot is NOT pointing to the releases/current/htdocs/web but instead parts of the deployment are symlinked into a foreign documentRoot. Don't ask. Just mentioning this for completion's sake.

**Comment by simonschaufi** [comment]
Please checkout this pr and try it: https://github.com/TYPO3/Surf/pull/403 and set 'webDirectory' to 'web'.

**Comment by fe-hicking** [comment]
Ok, will do that on friday. Thanks! However having this as a breaking change (due to people’s „webDirectory“ mismatching then) looks a bit more problematic to me than a patch using a new/unused config option?

**Comment by simonschaufi** [comment]
I would say it is very very rare that people use sub directories as project root path

**Comment by fe-hicking** [comment]
That might be true, but a breaking change sadly is a breaking change... and at least for us it would break about two dozen deployments. Without usage tracking we couldn‘t infer how many people use the option how. Others like us could have used their own InstallTasks, too, while relying on the „webdirectory“ setting.

(I only want to point out the BC break, I‘m not saying this isn‘t a viable route to go, and greatly appreciate your input and help on this)

**Comment by simonschaufi** [comment]
No this is non breaking as I don't change any defaults. When you set the project root path, then you also need to adjust the web directory but if you don't set the project root path, everything will still work like before.

**Comment by fe-hicking** [comment]
Ooh! I understand now. Sorry, too tired. Will try it with clear eyes and a full heart and shut up until then. Thanks for clarifying.

**Comment by simonschaufi** [comment]
I have setup a project with a typo3 in htdocs subdirectory setting webDirectory to 'htdocs/web' but I'm stuck in SetUpExtensionsTask where typo3 console couldn't be found. That is what i said initially, I wonder how many changes you made yourself to make that work.

**Comment by fe-hicking** [comment]
Here's a dummy repository I created with the most simple deployment example as how it should work (without your current patch applied):

https://github.com/faktore-git/demosurfer

The only patch we made is to acommodate the composer.json location through the 2 lines in InstallTask.php. All the rest is deployment configuration supported through Surf.

**Comment by simonschaufi** [comment]
ok now I see that you also changed the path to typo3 console. If you apply my patch, then you just need to add the new configuration added by me and remove htdocs everywhere from your config and it should work the same.

**Comment by fe-hicking** [comment]
Closed, superseded by https://github.com/TYPO3/Surf/pull/403

**Pull request closed without merging**
