### PR TITLE
Allow usage with PHP 7.3

### PR DESCRIPTION
**Pull request by christoph-bessei**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Allow usage with PHP 7.3 (bump composer.json restriction)

* **What is the current behavior?** (You can also link to an open issue here)
PHP 7.3 not supported

* **What is the new behavior (if this is a feature change)?**
PHP < 7.4 supported

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

### CODE REVIEW

**Comment by sabbelasichon** [comment]
@christoph-bessei Thanks. Could you also update the travis-ci.yml in order to see if it really works with  7.3.

**Comment by christoph-bessei** [comment]
Sure.

Which PHP versions should be tested with ```env: PHPUnit=latest```?
Only 7.3 or 7.2 and 7.3?

**Comment by sabbelasichon** [comment]
@christoph-bessei 

I would say both 7.2. and 7.3.

**Comment by sabbelasichon** [comment]
@christoph-bessei 

You have to update the composer.lock file also. Then it should work.

**Comment by christoph-bessei** [comment]
Is it fine to just run ```composer update```? 
This would change a lot of locked dependencies, but I can't update ```php-cs-fixer``` only, because it conflicts with the current locked version of ```symfony/console```.

**Comment by sabbelasichon** [comment]
@christoph-bessei I have to look into this carefully. Otherwise we are going to break a lot.

I would recommend that you are going to use the surf.phar file. To install surf as composer dependency is not recommended.

**Comment by christoph-bessei** [comment]
Dependency hell :-)
I will try to find a configuration which works in 5.6 - 7.3 without updating all dependencies.

**Comment by christoph-bessei** [comment]
@sabbelasichon Next attempt, this time with minimal changes. What do you think?

**Comment by josefglatz** [comment]
@sabbelasichon Is there anything else to check to get PHP 7.3 officially supported?

**Comment by sabbelasichon** [comment]
@josefglatz This is now handled by https://github.com/TYPO3/Surf/pull/313. Should be doable. Waiting for a review by @t3easy

**Pull request closed without merging**
