### PR TITLE
[TASK] Use recommended way to install PHP CS Fixer

### PR DESCRIPTION
**Pull request by t3easy**
The recommended way to install PHP CS Fixer is to use Composer in a dedicated composer.json file in your project,
for example in the tools/php-cs-fixer directory.

### CODE REVIEW

**Comment by simonschaufi** [comment]
Why is this recommended?
Secondly, Sebastian proposed a different tool already.

**Comment by t3easy** [comment]
Because that's what the documentation tells: https://github.com/FriendsOfPHP/PHP-CS-Fixer#installation

This prevents dependency problems with libraries used by Surf and PHP CS Fixer.

**Comment by jonaseberle** [comment]
Do we have problems with conflicting libraries in Surf?

I would keep it where it is as long as it does not make problems. 
(If I get problems with tools in projects, I use `bamarni/composer-bin-plugin`.)

**Comment by t3easy** [comment]
> Do we have problems with conflicting libraries in Surf?
> 
> 
> 
> I would keep it where it is as long as it does not make problems. 
> 
> (If I get problems with tools in projects, I can recommend `bamarni/composer-bin-plugin`.)

Why not just follow the recommendation of the vendor?

It's like others not following the documentation/examples of surf and wondering if something not working as expected.

**Comment by jonaseberle** [comment]
It is not really important for me but I don't agree with the reasoning. Sure that recommendation is theoretically valid because `php-cs-fixer` could live in its own runtime environment thus preventing dependency hell. The the recommendation shows that the developer wants to safe users from that potential problem which is a nice intention. 

But the same would be true for any other linter. 

Why not just keep it in --dev as long as it is not interfering with Surf dependencies? 

And if it should be moved to its own environment, [`bamarni/composer-bin-plugin`](https://github.com/bamarni/composer-bin-plugin#example) is a more convenient way to achieve the same because it keeps the command in the convenient `./vendor/bin` location while still isolating it from other dependencies.

**Comment by sabbelasichon** [comment]
I would also keep it as it is. I never had any problems with it

**Pull request closed without merging**
