### PR TITLE
!!! TASK: Don’t run Neos site import by default in Neos apps

### PR DESCRIPTION
**Pull request by Sebobo**

### CODE REVIEW

**Comment by Sebobo** [comment]
This resolves #227

**Comment by sabbelasichon** [comment]
@Sebobo Do we need to document this change in the Migrations folder?

**Comment by kaystrobach** [comment]
Was it activated in the beginning? In v1? If not i would just make a small hint in the docs, which default tasks are executed.

**Comment by Sebobo** [comment]
Yes it was always there and that's why nobody really used this app and instead used the Flow App or removed the task.

I'll add a note.

**Pull request merged**
