### PR TITLE
[BUGFIX] Add component symfony/finder explicitly

### PR DESCRIPTION
**Pull request by sabbelasichon**

### CODE REVIEW

**Comment by simonschaufi** [comment]
@sabbelasichon If surf runs without the dependency, wouldn't it be better to require that as dev-dependency only? My understanding was that it is only required when you build the phar, right?

**Comment by t3easy** [comment]
Surf needs the finder to use services.yml for DI, see https://github.com/TYPO3/Surf/runs/845466345?check_suite_focus=true#step:9:4

**Comment by simonschaufi** [comment]
There is definitely no finder installed as the lock entry doesn't contain it. Could it be that it is still used as I have it installed in composer global directory?

**Comment by t3easy** [comment]
Did you install with dev packages?
Because friendsofphp/php-cs-fixer installs it and dependencies of dev-dependencies seems not to been locked.

**Comment by simonschaufi** [comment]
ah right, I looked in the wrong composer.lock file :smiley: I have a main one that requires `typo3/surf` but within I also executed composer install once. That's why the `var` folder is also filled where the DI stuff is inside.

**Pull request merged**
