### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by sabbelasichon**
Resolves: #456

### CODE REVIEW

**Comment by simonschaufi** [comment]
@sabbelasichon sadly you messed up some doccomments

**Comment by sabbelasichon** [comment]
> @sabbelasichon sadly you messed up some doccomments 

What do you mean?

**Comment by simonschaufi** [comment]
`/* xxx */` became `//` in some places

**Comment by sabbelasichon** [comment]
I see. That was PHP-CS-Fixer. But the comment was wrong anyways. It should have been /** xxx */. Right?
Anyways. We could change it back if it hurts.

**Comment by simonschaufi** [comment]
Yes please as `//` is not a doccomment

**Comment by sabbelasichon** [comment]
It is fixed in master.

**Pull request merged**
