### PR TITLE
[BUGFIX] Fix master for deployment of TYPO3 11.5 with TYPO3 Console 7.0 and option "extensionKeys"

### PR DESCRIPTION
**Pull request by mz-aimcom**
Related: #450

### CODE REVIEW

**Comment by simonschaufi** [comment]
Please write a test for this

**Comment by mz-aimcom** [comment]
> Thank you for your contribution. Could you please write a test for this?

Yes, I will try. My colleague also found a possible problem when no extension keys are submitted and TYPO3 Console version 7+ is used (will result in a call of `extension:setupactive`, which does not exist anymore). I'll also have a look at that.

**Comment by mz-aimcom** [comment]
I'm not that sure. I think they "redirect" to the core command: https://github.com/TYPO3/typo3/blob/master/typo3/sysext/extensionmanager/Classes/Command/SetupExtensionsCommand.php

**Comment by t3easy** [comment]
But I guess the patch would break deployments with TYPO3 v9/v10 and typo3-console 5/6?

**Comment by mz-aimcom** [comment]
> But I guess the patch would break deployments with TYPO3 v9/v10 and typo3-console 5/6?

Yes, that's what my colleague also supposed. The current change is missing a condition to check the TYPO3 and/or console version. I will close this pull request and check/resolve that issue.

**Comment by t3easy** [comment]
Maybe a temporary workaround would be to put the `-e` to the comma separated list, e.g. `-e,ext1,-e,ext2`

**Comment by mz-aimcom** [comment]
> I will close this pull request and check/resolve that issue. I will re-open it when the change is ready...

The change is ready ([commit `cf1236e1`](https://github.com/mz-aimcom/Surf/commit/cf1236e1f73caa069d47cfd637484af90ddb3675)) and I also managed to update the unit tests ([commit `d13f074e`](https://github.com/mz-aimcom/Surf/commit/d13f074e92ed721184d4062447746fe59047d264)).

**Comment by mz-aimcom** [comment]
@simonschaufi Hi, do you think it's OK now? I updated the `SetUpExtensionsTaskTest.php` so that the inserted conditions are checked.

**Comment by mz-aimcom** [comment]
> @simonschaufi Hi, do you think it's OK now? I updated the `SetUpExtensionsTaskTest.php` so that the inserted conditions are checked (see [my last post](https://github.com/TYPO3/Surf/pull/452#issuecomment-976339931)).

@jonaseberle @simonschaufi @t3easy Hi there, can I provide anything else to get this fix pulled? :)

**Comment by jonaseberle** [comment]
Sorry, I can't really comment since I don't use v11 outside of extension/core dev.

**Comment by sabbelasichon** [comment]
@mz-aimcom Thanks a lot for your Pull Request. I have used as an inspiration for another Pull Request. Especially the tests i have simplified a lot. I know it is quite obscure how Surf asserts the execution of the commands. I always forget it myself when doing this. Have a look at: https://github.com/TYPO3/Surf/pull/460/files

**Comment by mz-aimcom** [comment]
> @mz-aimcom Thanks a lot for your Pull Request. I have used as an inspiration for another Pull Request. Especially the tests i have simplified a lot. I know it is quite obscure how Surf asserts the execution of the commands. I always forget it myself when doing this. Have a look at: https://github.com/TYPO3/Surf/pull/460/files
> 
> I hope you are not disappointed by closing your PR. The fix is your achievement.

Hi @sabbelasichon , no disappointment at all. I'm glad I was able to help and support this nice tool. Thanks for your final fix.👍

**Pull request closed without merging**
