### PR TITLE
[TASK] Clean up CopyConfiguration task

### PR DESCRIPTION
**Pull request by SomeBdyElse**
* Remove dysfunctional functionality to copy configuration subdirectories
* Deal with whitespaces in local and remote paths

### CODE REVIEW

**Comment by SomeBdyElse** [comment]
I just realized that https://github.com/TYPO3-Surf-CMS/Surf.CMS/blob/master/Packages/Application/TYPO3.Surf.CMS/Classes/TYPO3/Surf/CMS/Task/TYPO3/CMS/CopyConfigurationTask.php has a version of the CopyConfigurationTask, where the functionality to recurse through subdirectories might actually work. 

Instead of `glob('*')`, which only retrieves children of the configuration directory, the Surf.CMS version uses `\TYPO3\Flow\Utility\Files::readDirectoryRecursively`. I assume the functionality broke when the script was migrated from away from Flow to Surf standalone. I will update my pull request to fix the subdirectory functionality instead of removing it. 

So please do not merge this quite yet.

**Comment by helhum** [comment]
Cool! Thanks a lot. Your pull requests look all good, I'm only on holiday right now that is because I could not have a closer look yet.

**Comment by helhum** [comment]
This was indeed a bit more complicated than expected. Can you please verify current master with my fix?

**Comment by SomeBdyElse** [comment]
Now it's just me, who is on holidays. Please don't expect a reply before 1 April. Thanks!

**Comment by helhum** [comment]
Sure! Happy easter :)

**Pull request closed without merging**
