### PR TITLE
Use the phpBinaryPathAndFilename option for primary flow script calls

### PR DESCRIPTION
**Pull request by martinlipp**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
#303 

* **What is the new behavior (if this is a feature change)?**
The php binary to be used for primary flow script calls can be defined now.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No.

* **Other information**:

### CODE REVIEW

**Comment by martinlipp** [comment]
> There is no space between the context and the php binary.

The space is in the $phpBinaryPathAndFilename variable.

**Comment by t3easy** [comment]
The RunCommandTask also use an own 

> > There is no space between the context and the php binary.
> 
> The space is in the $phpBinaryPathAndFilename variable.

Yes, sorry just saw it. And thank you for your very quick response!
I'm looking over the Neos tasks right now...
E.G. some tasks build the commad w/o the app->buildCommand https://github.com/TYPO3/Surf/blob/master/src/Task/Neos/Flow/RunCommandTask.php#L66
This must also be adapted, too... To use the same function at best.
And we nees some tests.

**Comment by t3easy** [comment]
And https://github.com/TYPO3/Surf/blob/master/src/Task/Neos/Flow/FlushCacheListTask.php#L67-L70
... we should standardize that.

**Comment by martinlipp** [comment]
I also found those two tasks. I don't see a reason against simply using the buildCommand method in these tasks also. What do you think?
Regarding tests: I've never done test driven development. Should I simply extend the executeWithDifferentOptions array in the RunCommandTaskTest and SetFilePermissionsTaskTest to check if the phpBinaryPathAndFilename option is used correctly? Or check for that in all tests that run the flow script? Or a do it with a whole new test?

**Comment by t3easy** [comment]
I have a few changes that haven't push yet because I'd like to get #307 merged first.

**Comment by t3easy** [comment]
I unified the tasks to use the command builder of the application. Maybe a Flow/Neos user could review?

**Comment by t3easy** [comment]
I'll merge this tomorrow if there is no veto.

**Pull request merged**
