### PR TITLE
[TASK] Remove CreatePackageStatesTask (#368)

### PR DESCRIPTION
**Pull request by simonschaufi**
Fixes: #368 

Migrate: Please add "@php vendor/bin/typo3cms install:generatepackagestates" in
your root composer.json file in the post-autoload-dump scripts section.

### CODE REVIEW

**Comment by t3easy** [comment]
Then we should deprecate the task in 2.0.

**Comment by simonschaufi** [comment]
How should we let the user know about the deprecation?

**Comment by t3easy** [comment]
Add depreciation warning to the task in 2.0 branch and release a hotfix version.

**Comment by simonschaufi** [comment]
I will do that.

**Pull request merged**
