### PR TITLE
Fix SetUpExtensionsTask for TYPO3 Console Version >= 7

### PR DESCRIPTION
**Pull request by sabbelasichon**

### CODE REVIEW

**Comment by simonschaufi** [comment]
@sabbelasichon Have you ever tried this out, actually? It doesn't work for me because the TYPO3 Console outputs its version like so:

```
vendor/bin/typo3cms --version
TYPO3 Console 7.3.0
TYPO3 CMS 11.5.0 (Application Context: Production)
```

and this results in a one liner and therefore the actual console version is `0.0.0`

**Comment by sabbelasichon** [comment]
Yes. Tried it and it worked. The version output was a one liner. Gonna write a test for your output.

**Comment by t3easy** [comment]
I had the idea to use something like `composer show --installed --format json` as a task after the composer install task to add information about all packages to the application. That information could be used later for example to get the version of Neos, TYPO3 Console or other..

**Comment by sabbelasichon** [comment]
@simonschaufi Does this  PR fixes the issue for you: https://github.com/TYPO3/Surf/pull/481/files

**Comment by mz-aimcom** [comment]
> @sabbelasichon Have you ever tried this out, actually? It doesn't work for me because the TYPO3 Console outputs its version like so:
> 
> ```
> vendor/bin/typo3cms --version
> TYPO3 Console 7.0.5
> TYPO3 CMS 11.5.7 (Application Context: Production)
> ```
> 
> and this results in a one liner and therefore the actual console version is `0.0.0` because the version detection crashes with the input string: `7.0.5\nTYPO3 CMS 11.5.7 (Application Context: Production)`

I can confirm the issue.

In my test setup, the output of `./vendor/bin/typo3cms --version` is this:
```
TYPO3 Console 7.0.5
TYPO3 CMS 11.5.7 (Application Context: Production)
```

In my old pull request, the output was limited to the first line (see [PR #452](https://github.com/TYPO3/Surf/pull/452/commits/cf1236e1f73caa069d47cfd637484af90ddb3675#diff-4a022af7e0710b87f00f93c49d8aed34a09dd3b98ce7dd2517deaa2f7a6c879bR105)).
Pull request #481 looks good and is working for me.👍💪

**Comment by simonschaufi** [comment]
@sabbelasichon works! Thanx :heart_eyes:

**Pull request merged**
