### PR TITLE
[FEATURE] Use captain hook for githooks

### PR DESCRIPTION
**Pull request by sabbelasichon**
The old mechanism with make and folder .githooks to create githooks for every developer is very fragile. A lot of people forget to install it.
With the new approach it is more reliable that everyone is on the same track.

### CODE REVIEW

**Comment by simonschaufi** [comment]
With that PR some files will be duplicated like this one:

`Documentation/ApiReference/Application/BaseApplication.rst` and `Documentation/ApiReference/TYPO3/Surf/Application/BaseApplication.rst`

Imho the first one should be deleted.

**Comment by t3easy** [comment]
I don't get it at all why this have to run local.
As you like to switch to github actions, why not use the action https://github.com/marketplace/actions/create-pull-request to run the tasks and send a PR to the tested branch.

**Comment by simonschaufi** [comment]
Do we actually need an API reference? That just blows up the docs which nobody will read.

**Comment by sabbelasichon** [comment]
Ok, i am going to close this PR and we really should drop the generated API Reference. We are relying on a very old unmaintained project sphpdox. I tested it already with PHP7 return type declarations and it didn´t work. I don´t want to miss out the usage of this feature due to the fact that the library doesn´t support it.

**Pull request closed without merging**
