### PR TITLE
[TASK] Composer dump-autoload task added with additional arguments

### PR DESCRIPTION
**Pull request by Cyb10101**
Dumps the autoload. (composer dump-autoload --optimize)

composer.json
```
{
	"autoload": {
		"psr-4": {
			"Namespace\\ExtKey\\": "typo3conf/ext/ext_key/Classes"
		}
	}
}
```

### CODE REVIEW

**Comment by helhum** [comment]
Could you outline what the purpose of this task is, compared to the already available composer install task?

**Comment by Cyb10101** [comment]
If you add a PSR-0/4 manualy in composer.json and can't install/update a package, because you already up to date. So you can update only the autoloader files.
https://getcomposer.org/doc/03-cli.md#dump-autoload

**Comment by helhum** [comment]
I'm sorry, I seem to still not understand. 

> If you add a PSR-0/4 manualy in composer.json

Add this where exactly, when and how?

> and can't install/update a package, because you already up to date

I don't get this either. What package? And why wouldn't a composer install work?


Can you outline your deployment scenario a bit? Thanks.

**Comment by kitsunet** [comment]
> If you add a PSR-0/4 manualy in composer.json
I guess I understand what is meant and that is a hack, why wouldn't you just commit the changes to the autoload configuration?

Apart from this intention a `dump-autoload --optimize` task is nice to have. What it does is to traverse defined autoload directories of all packages and collect the found classes in a static map for faster autoloading.

I would suggest to name the method `buildComposerInstallCommand` differently though, as this is not an install commnd.

**Comment by kitsunet** [comment]
NVM, the default install task does it already. In that case I also see not much use for this...

**Comment by helhum** [comment]
> I guess I understand what is meant and that is a hack, why wouldn't you just commit the changes to the autoload configuration?

How would uncommitted changes end up in the deployment chain anyway currently? Still lacking some bit of information :)

> Apart from this intention a `dump-autoload --optimize` task is nice to have

I indeed thought about making the `--optimize` flag configurable in the composer **install** task.
I did not do so, because it is possible to put this config into your root composer.json to achieve the same result:

```json
"config": {
	"optimize-autoloader": true
}
```

But why would a dedicated `composer dump-autoload` make sense, if this happens during `composer install` anyway? At what point during deployment would such a task be executed?

**Comment by helhum** [comment]
> NVM, the default install task does it already. In that case I also see not much use for this...

Ah, ok thanks :)

**Comment by kitsunet** [comment]
Just as a follow up: I assume the following situation: deploy from local machine without actual install task (besides this one here) and just rsync. In that case no actual composer install happens and you could deploy uncomitted changes... Still nothing I would want to support.

**Comment by helhum** [comment]
> without actual install task (besides this one here) and just rsync

That is not possible currently, at least not easily out of the box.

> In that case no actual composer install happens and you could deploy uncomitted changes

That might be useful as simplest deployment workflow. Just pushing the local state to the server.

But doing a deployment of a state that would not work locally, is something I don't really understand :)

**Comment by Cyb10101** [comment]
Cool, that's much better. Thank you ;-)

**Pull request closed without merging**
